"""Tests driven by the shared test_vectors.json file.

This is the cross-language validation source of truth,
generated by Python and consumed by JS, PY, and C.
"""

import json
from pathlib import Path

import pytest

from carrymath import (
    bfs_simple,
    bulk_covariance,
    carry_chain,
    carry_polynomial,
    carry_polynomial_coeffs,
    convolution,
    discrete_log,
    divisor_component,
    euler_totient,
    from_digits,
    induction_step,
    legendre_symbol,
    modular_matrix_row,
    multiplicative_order,
    phantom_counts,
    poly_roots_mod,
    primitive_root,
    to_digits,
    verify_lemma_d,
)

_VECTORS_PATH = Path(__file__).resolve().parent / "data" / "test_vectors.json"
with open(_VECTORS_PATH) as f:
    VECTORS = json.load(f)


class TestCarryVectors:
    @pytest.fixture(params=VECTORS["carry_vectors"], ids=lambda v: f"{v['p']}*{v['q']}")
    def v(self, request):
        return request.param

    def test_digits_p(self, v):
        assert to_digits(v["p"], v["base"]) == v["digits_p"]

    def test_digits_q(self, v):
        assert to_digits(v["q"], v["base"]) == v["digits_q"]

    def test_digits_N(self, v):
        assert to_digits(v["N"], v["base"]) == v["digits_N"]

    def test_from_digits_roundtrip(self, v):
        assert from_digits(v["digits_p"], v["base"]) == v["p"]
        assert from_digits(v["digits_q"], v["base"]) == v["q"]

    def test_carry_chain(self, v):
        cc = carry_chain(v["digits_p"], v["digits_q"], v["base"])
        assert cc == v["carry_chain"]

    def test_convolution(self, v):
        if not v["convolution"]:
            pytest.skip("empty convolution vector")
        conv = convolution(v["digits_p"], v["digits_q"])
        assert conv == v["convolution"]

    def test_carry_polynomial(self, v):
        cp = carry_polynomial(v["p"], v["q"], v["base"])
        assert cp == v["carry_polynomial"]

    def test_carry_polynomial_coeffs(self, v):
        cc = carry_polynomial_coeffs(v["p"], v["q"], v["base"])
        assert cc == v["carry_polynomial_coeffs"]


class TestNumberTheoryVectors:
    @pytest.mark.parametrize("n,expected", VECTORS["number_theory"]["euler_totient"])
    def test_euler_totient(self, n, expected):
        assert euler_totient(n) == expected

    @pytest.mark.parametrize("p,expected", VECTORS["number_theory"]["primitive_root"])
    def test_primitive_root(self, p, expected):
        assert primitive_root(p) == expected

    @pytest.mark.parametrize("a,p,expected", VECTORS["number_theory"]["legendre_symbol"])
    def test_legendre_symbol(self, a, p, expected):
        assert legendre_symbol(a, p) == expected

    @pytest.mark.parametrize("a,n,expected", VECTORS["number_theory"]["multiplicative_order"])
    def test_multiplicative_order(self, a, n, expected):
        assert multiplicative_order(a, n) == expected

    @pytest.mark.parametrize("x,g,p,expected", VECTORS["number_theory"]["discrete_log"])
    def test_discrete_log(self, x, g, p, expected):
        assert discrete_log(x, g, p) == expected

    @pytest.mark.parametrize("coeffs,m,expected_roots", VECTORS["number_theory"]["poly_roots_mod"])
    def test_poly_roots_mod(self, coeffs, m, expected_roots):
        assert sorted(poly_roots_mod(coeffs, m)) == expected_roots


class TestEntropyVectors:
    @pytest.fixture(params=VECTORS["entropy"], ids=lambda v: f"N={v['N']}")
    def v(self, request):
        return request.param

    def test_bfs_simple(self, v):
        assert bfs_simple(v["N"], v["maxPos"]) == v["S0"]

    def test_divisor_component(self, v):
        assert divisor_component(v["N"], v["maxPos"]) == v["tau"]

    def test_phantom_counts(self, v):
        assert phantom_counts(v["N"], v["maxPos"]) == v["phantom"]


class TestCovarianceVectors:
    def test_bulk_covariance_j3(self):
        cv = VECTORS["covariance"]
        r = bulk_covariance(cv["K"])
        from fractions import Fraction

        assert r["cov"][3] == Fraction(cv["cov_j3"][0], cv["cov_j3"][1])

    def test_lemma_d(self):
        cv = VECTORS["covariance"]
        r = verify_lemma_d(3)
        assert r["lemma_d_holds"] == cv["lemma_d_K3"]

    def test_induction_step(self):
        cv = VECTORS["covariance"]
        from fractions import Fraction

        r = induction_step(cv["K"])
        assert r[1] == Fraction(cv["induction_step_j1"][0], cv["induction_step_j1"][1])


class TestModularMatrixRowVectors:
    @pytest.mark.parametrize("v", VECTORS["modular_matrix_row"])
    def test_modular_matrix_row(self, v):
        result = list(modular_matrix_row(v["N"], v["row"], v["width"]))
        assert result == v["result"]
